name: React App CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        run: |
          curl -H "Authorization: Bearer ${{ secrets.API_KEY }}" https://api.example.com/deploy

  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Node.js and install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # 사용할 Node.js 버전

      - name: Install dependencies
        run: npm install

      # 3. Run tests
      - name: Run tests
        run: npm test -- --ci --silent

      # 4. Build the app for production
      - name: Build the app
        run: npm run build